export const mockUser = (overrides: Record<string, any> = {}) => ({
  id: 1,
  username: 'testuser',
  name: 'Test User',
  password: '$2b$10$hashedpassword',
  role: 'STAFF',
  pin: '1234',
  isActive: true,
  branchId: 1,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  ...overrides,
});

export const mockOrder = (overrides: Record<string, any> = {}) => ({
  id: 1,
  orderId: 'ORD-TEST-001',
  status: 'PENDING',
  totalAmount: 250,
  totalItems: 3,
  tableNumber: 'A1',
  branchId: 1,
  sessionId: null,
  splitFromOrderId: null,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  items: [
    mockOrderItem(),
    mockOrderItem({ id: 2, menuItemId: 2, price: 100 }),
  ],
  payments: [],
  ...overrides,
});

export const mockOrderItem = (overrides: Record<string, any> = {}) => ({
  id: 1,
  orderId: 1,
  menuItemId: 1,
  quantity: 1,
  price: 150,
  status: 'PENDING',
  specialInstructions: null,
  diningOption: null,
  selectedAddOns: null,
  selectedAddOnGroups: null,
  selectedNestedOptions: null,
  menuItem: { id: 1, name: 'Test Menu Item', price: 150 },
  ...overrides,
});

export const mockPayment = (overrides: Record<string, any> = {}) => ({
  id: 1,
  receiptNumber: 'RCP-20260101-001',
  orderId: 1,
  branchId: 1,
  paymentMethod: 'CASH',
  paymentStatus: 'PAID',
  subtotal: 250,
  serviceCharge: 0,
  vat: 0,
  discountAmount: 0,
  discountPoints: 0,
  totalAmount: 250,
  paidAmount: 300,
  changeAmount: 50,
  memberId: null,
  memberName: null,
  pointsEarned: 0,
  cashierName: 'Admin',
  note: null,
  shiftId: null,
  promotionId: null,
  promotionDiscount: 0,
  promotionName: null,
  couponCode: null,
  mergedOrderIds: null,
  splitPayments: null,
  paidAt: new Date('2026-01-01'),
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  order: {
    id: 1,
    orderId: 'ORD-TEST-001',
    tableNumber: 'A1',
    items: [],
  },
  ...overrides,
});

export const mockIngredient = (overrides: Record<string, any> = {}) => ({
  id: 1,
  name: 'Rice',
  unit: 'kg',
  currentStock: 100,
  minStock: 10,
  costPerUnit: 50,
  isActive: true,
  branchId: 1,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  ...overrides,
});

export const mockRecipe = (overrides: Record<string, any> = {}) => ({
  id: 1,
  menuItemId: 1,
  ingredientId: 1,
  quantityUsed: 0.5,
  ingredient: mockIngredient(),
  menuItem: { name: 'Fried Rice' },
  ...overrides,
});

export const mockShift = (overrides: Record<string, any> = {}) => ({
  id: 1,
  shiftNumber: 'SH-20260101-001',
  userId: 1,
  cashierName: 'Admin',
  status: 'OPEN',
  branchId: 1,
  openingAmount: 1000,
  openingCashCount: null,
  closingAmount: null,
  closingCashCount: null,
  closingNotes: null,
  expectedCashAmount: null,
  cashDifference: null,
  totalRevenue: null,
  totalOrders: null,
  cashTotal: null,
  transferTotal: null,
  creditCardTotal: null,
  notes: null,
  openedAt: new Date('2026-01-01T08:00:00'),
  closedAt: null,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  ...overrides,
});
