version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: food-ordering-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_ordering
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: food-ordering-rabbitmq
    restart: unless-stopped
    hostname: food-ordering-rabbitmq
    ports:
      - '0.0.0.0:5673:5672'
      - '0.0.0.0:15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: nathee
      RABBITMQ_DEFAULT_PASS: nathee
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
