services:
  food-ordering-db:
    image: postgres:15-alpine
    container_name: food-ordering-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_ordering
    volumes:
      - postgres_data:/var/lib/postgresql/data

  food-ordering-rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: food-ordering-rabbitmq
    restart: unless-stopped
    hostname: food-ordering-rabbitmq
    ports:
      - '0.0.0.0:5673:5672'
      - '0.0.0.0:15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: nathee
      RABBITMQ_DEFAULT_PASS: nathee
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  food-ordering-redis:
    image: redis:7-alpine
    container_name: food-ordering-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
